# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v1

     - name: Add remote origin
       run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

     - name: Deploy backend to heroku
       run: git push --force heroku HEAD:master

     - name: Slack
       run: "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Succesfully deployed new version to Heroku - https://rettiprod.herokuapp.com/\"}' https://hooks.slack.com/services/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"
