# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: chatops-test
        SLACK_COLOR: '#3278BD'
        SLACK_ICON: https://images.homedepot-static.com/productImages/81e74102-faa7-438a-a45a-d1fbdecee879/svn/electronics-cleaning-care-ac1016a-ys-64_1000.jpg
        SLACK_MESSAGE: 'Mye tøffere chatops :rocket: :score :win :first'
        SLACK_TITLE: More chat more ops!
        SLACK_USERNAME: Yellow Submarine
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
    - uses: act10ns/slack@v1.0.9
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        status: "Build Failed bigtime :sadparrot: "
        channel: '#chatops-test'
      if: failure()

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v1

     - name: Add remote origin
       run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

     - name: Deploy backend to heroku
       run: git push --force heroku HEAD:master

     - name: slack - GitHub Actions Slack integration
        # You may pin to the exact commit or the version.
        # uses: act10ns/slack@a59542b0f7f766e6b16c9c6bf433ecd2f2f35f06
       uses: act10ns/slack@v1.0.9
       env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
       with:
         status: ${{ job.status }}
          # Override default channel with different channel or username
         channel: '#chatops-test'
